export const galleryItems = [
  {
    id: "1",
    preview: "https://i.ibb.co/xCn89H2/image.png",
    original: "https://i.ibb.co/xCn89H2/image.png",
    name: "Муся",
    date: "3 апреля 2010г.",
    icon: "cat",
  },
  {
    id: "2",
    preview: "https://i.ibb.co/8YqWSFR/image.png",
    original: "https://i.ibb.co/8YqWSFR/image.png",
    name: "Ума",
    date: "26 июня 2010г.",
    icon: "dog",
  },
  {
    id: "3",
    preview: "https://i.ibb.co/1nMr3Yf/image.png",
    original: "https://i.ibb.co/1nMr3Yf/image.png",
    name: "Рыжий",
    date: "8 июля 2010г.",
    icon: "cat",
  },
  {
    id: "4",
    preview: "https://i.ibb.co/kMpRXDD/IMAG0049.jpg",
    original: "https://i.ibb.co/kMpRXDD/IMAG0049.jpg",
    name: "Ума",
    date: "8 марта 2012г.",
    icon: "dog",
  },
  {
    id: "5",
    preview: "https://i.ibb.co/kcfNvJP/IMAG0050.jpg",
    original: "https://i.ibb.co/kcfNvJP/IMAG0050.jpg",
    name: "Рыжий",
    date: "8 марта 2012г.",
    icon: "cat",
  },
  {
    id: "6",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
    icon: "cat",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
    icon: "cat",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
    icon: "cat",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
    icon: "cat",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
    icon: "cat",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
  {
    id: "",
    preview: "",
    original: "",
    name: "",
    date: "2010г.",
  },
];
